# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Format
      run: dotnet format --verify-no-changes --verbosity diagnostic
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true
    - name: Coverage Report
      run: type D:\a\CalculatorApp\CalculatorApp\CalculatorApp.Test\coverage.json
    - name: Coverage Email
      uses: dawidd6/action-send-mail@v6
      with:
        server_address: smtp.asu.edu
        server_port: 465
        to: rtenriqu@asu.edu
        from: Richard Enriquez
        subject: Coverage Report
        body: Coverage report attached.
        attachments: D:\a\CalculatorApp\CalculatorApp\CalculatorApp.Test\coverage.json